default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:     db
  username: postgres
  password: password

development:
  <<: *default
  database: checkout_development

test:
  <<: *default
  database: checkout_test

production:
  <<: *default
  database: checkout_production
  username: checkout
  password: <%= ENV['CHECKOUT_DATABASE_PASSWORD'] %>
